### ISSUE TITLE
[REQUEST] Support for Nopecha Captcha Solver

### ISSUE THREAD

**Issue by Chappie18** [omkarcloud/outlook-account-generator#22]
Could you please include support for the Nopecha captcha solver.
**https://nopecha.com/**

**Comment by Chetan11-dev** [comment]
No

**Comment by Chappie18** [comment]
May I know the rationale for this response?
Considering that Nopecha offers free credit for usage, I believe it to be a better offer than other captcha solvers.

**Comment by Chetan11-dev** [comment]
Actually, the end user is likely to have limited knowledge about Captcha Solving. Therefore, instead of presenting them with multiple Captcha Solving options, let's offer just one. This approach will prevent confusion, and Capsolver is an good choice for a Captcha Solving.

However, should there be increased interest in this feature from more users in the future, I am open to reconsidering my decision.

**Comment by ROGUEREAPER86** [comment]
i'm definitely interested in adding support for it

**Comment by Chappie18** [comment]
> i'm definitely interested in adding support for it

Lately, all captcha solvers are experiencing difficulty completing Funcaptcha with shadow.

**Comment by Chetan11-dev** [comment]
I am closing this issue. Finally, if Capsolver does not fix Funcaptcha by January 3rd, I will attempt to implement an alternative captcha solver, such as 2Captcha or AnyCaptcha.
